// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {app} from '../models';
import {chapter} from '../models';
import {novel} from '../models';
import {config} from '../models';

export function ApproveTool(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function Chat(arg1:context.Context,arg2:app.ChatInput):Promise<app.ChatResult>;

export function CreateChapter(arg1:app.CreateChapterInput):Promise<chapter.Chapter>;

export function CreateNovel(arg1:app.CreateNovelInput):Promise<novel.Novel>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetChapters(arg1:number):Promise<Array<chapter.Chapter>>;

export function GetContent(arg1:number,arg2:string):Promise<string>;

export function GetNovels():Promise<Array<novel.Novel>>;

export function GetPlatform():Promise<Record<string, any>>;

export function GetSettings():Promise<config.AppSettings>;

export function Initialize(arg1:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function SaveContent(arg1:app.SaveContentInput):Promise<void>;

export function SaveSettings(arg1:app.SaveSettingsInput):Promise<void>;

export function SetActiveNovel(arg1:app.SetActiveNovelInput):Promise<void>;

export function SetApprovalMode(arg1:string):Promise<void>;
