// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {novel} from '../models';
import {chapter} from '../models';
import {config} from '../models';

export function Chat(arg1:number,arg2:string):Promise<string>;

export function CreateNovel(arg1:string,arg2:string):Promise<novel.Novel>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetChapters(arg1:number):Promise<Array<chapter.Chapter>>;

export function GetNovels():Promise<Array<novel.Novel>>;

export function GetPlatform():Promise<Record<string, any>>;

export function GetSettings():Promise<config.AppSettings>;

export function Initialize(arg1:string):Promise<void>;

export function IsInitialized():Promise<boolean>;

export function SaveSettings(arg1:string,arg2:string):Promise<void>;
