// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1, arg2) {
  return window['go']['app']['App']['Chat'](arg1, arg2);
}

export function CreateNovel(arg1, arg2) {
  return window['go']['app']['App']['CreateNovel'](arg1, arg2);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetChapters(arg1) {
  return window['go']['app']['App']['GetChapters'](arg1);
}

export function GetNovels() {
  return window['go']['app']['App']['GetNovels']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function Initialize(arg1) {
  return window['go']['app']['App']['Initialize'](arg1);
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function SaveSettings(arg1, arg2) {
  return window['go']['app']['App']['SaveSettings'](arg1, arg2);
}
