name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-ruff@v2
        with:
          version: latest
      - run: ruff check --select UP045,UP006,UP035,F401
